In [2]:
# 구글 마운트하기
from google.colab import drive
drive.mount('/content/drive')


# # 현재 경로 지정하기
import os
os.chdir('/content/drive/MyDrive/파트4')

Mounted at /content/drive

In [3]:
!pip install koreanize_matplotlib

Collecting koreanize_matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl.metadata (992 bytes)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from koreanize_matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->koreanize_matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize_matplotlib) (1.17.0)
Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 40.2 MB/s eta 0:00:00
Installing collected packages: koreanize_matplotlib
Successfully installed koreanize_matplotlib-0.1.1

In [4]:
import warnings
import koreanize_matplotlib
import pandas as pd
import plotly.express as px

In [5]:
# 경고 무시
warnings.filterwarnings("ignore")
%config lnlineBackend.figure_format = 'retina'

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)  # 출력할 너비를 넉넉하게 조정
pd.set_option('display.expand_frame_repr', False)  # 옆으로 길어져도 줄바꿈 없이 출력
pd.set_option('display.max_colwidth', None)  # 긴 문자열도 생략 없이 출력
API_KEY_PATH = '/home/project_yujin/high_project/sprintda03-yujin.json'

basic_eda_dataframe = ['accounts_attendance', 'accounts_blockrecord', 'accounts_failpaymenthistory', 'accounts_friendrequest', 'accounts_group', 'accounts_nearbyschool']

In [6]:
API_KEY_PATH = '/content/drive/MyDrive/파트4/sprintda03-yujin.json'

def get_df(db_name, table_name):
    table_name = pd.read_csv(
        f"gs://high_project/{db_name}/{table_name}.csv",
        storage_options={'token' : API_KEY_PATH}
        )
    return table_name

## 전처리된 device_properties df

In [7]:
device_properties = get_df('hackle','device_properties')

# deivice_id에 대한 중복행 삭제
drop_device_id = device_properties[device_properties[['device_id']].duplicated(keep=False)]['device_id'].unique().tolist()
device_properties = device_properties[~device_properties['device_id'].isin(drop_device_id)]

# id컬럼 삭제
device_properties.drop('id', axis=1)

                                   device_id device_model device_vendor
0       000007C9-E103-4EB5-9777-A9084D4952DF   iPhone14,7         Apple
1       00002245-458F-4CDD-8533-B448CD43DBD2   iPhone14,7         Apple
2       00012620-313A-4502-9F8D-8DAB7443215B   iPhone14,5         Apple
3       000137bc-80de-4bb5-b61d-df7f217a4501     SM-F711N       samsung
4       000227D6-B782-4367-91C4-486B76DF9E37   iPhone12,3         Apple
...                                      ...          ...           ...
252375  FFFE54E6-48F9-4262-A487-94E944B1B68C   iPhone14,4         Apple
252376  FFFE80D2-6B57-41AF-9CD6-8E616CC7BFDE   iPhone14,7         Apple
252377  FFFED16A-DAF6-40A1-865D-29C4D1302DA5   iPhone14,4         Apple
252378  FFFEEA5E-C4D9-4BB7-A9E4-3715455B69AD   iPhone12,8         Apple
252379  FFFEF44A-ADDD-42BB-9594-698C10FDDDA9   iPhone13,2         Apple

[251060 rows x 3 columns]

In [8]:
hackle_properties = get_df('hackle','hackle_properties')
hackle_properties

            id                            session_id                       user_id language   osname osversion versionname                             device_id
0            1          4OzYh3seq3VKytpSn5pvQkZNQii1                           NaN    ko-KR      iOS      16.0       2.0.0  590E7C79-CBA0-44D8-8BE3-3C9BFABBBC74
1            2          8QXy31PQxbW9qLzq0Y1dhR8Ypm52                       1046711    ko-KR      iOS    16.5.1       2.0.3  D5417226-F71B-4A9E-A180-CD072F2AB279
2            3  6bcea65d-9f40-46fc-888c-700fe707483f                       1545130       ko  Android        13       2.0.5  6bcea65d-9f40-46fc-888c-700fe707483f
3            4          XVYNT6zfhFWqIg9omwg2AHDjTLx2                       1224793       ko  Android        13       2.0.5  a05c1595-3e05-434b-8684-218b528bd725
4            5          XFB2SPiGfjbVhvJ3Q3DBsaT3m2B3                       1329450    ko-US      iOS    16.5.1       2.0.5  EAC6C0B3-7CE8-40EA-8A91-9977C0BA5EF3
...        ...                                   ...                           ...      ...      ...       ...         ...                                   ...
525345  525346          KlGJxOfY4XdbxnwzPckMh4NdwBk2                       1373831    ko-KR      iOS    16.5.1       2.0.5  2EB9127D-703A-495B-8A1E-6667ACA9E724
525346  525347          HGxbSi2oq4MdFVGdQx2UH3f9Aq73                       1043127    en-KR      iOS    16.1.2       2.0.3  4400D84D-0353-49C9-818E-6A45D54F1039
525347  525348  F9EA195C-862F-4572-80A5-C3AE06F83310                           NaN    ko-KR      iOS    16.3.1       2.0.5  F9EA195C-862F-4572-80A5-C3AE06F83310
525348  525349          gQ5GvGk7kGWwnQbOzQ8fxseQp8B2  7m8IwV5H3aaxr1bdPbbkvvJMvtf2       ko  Android        12      1.2.15  eca30324-3b48-41a6-9628-ff663896dd23
525349  525350          8jROJMvKQMgiXMvrXvqDD7o0iWr2                        895807    ko-KR      iOS      16.0       2.0.0  B39CEB8B-2414-4018-91B8-CE1A75F1CCEE

[525350 rows x 8 columns]

In [ ]:
hackle_properties
hackle_properties = hackle_properties[['id', 'user_id', 'session_id', 'device_id']]

            id                            session_id                       user_id language   osname osversion versionname                             device_id
0            1          4OzYh3seq3VKytpSn5pvQkZNQii1                           NaN    ko-KR      iOS      16.0       2.0.0  590E7C79-CBA0-44D8-8BE3-3C9BFABBBC74
1            2          8QXy31PQxbW9qLzq0Y1dhR8Ypm52                       1046711    ko-KR      iOS    16.5.1       2.0.3  D5417226-F71B-4A9E-A180-CD072F2AB279
2            3  6bcea65d-9f40-46fc-888c-700fe707483f                       1545130       ko  Android        13       2.0.5  6bcea65d-9f40-46fc-888c-700fe707483f
3            4          XVYNT6zfhFWqIg9omwg2AHDjTLx2                       1224793       ko  Android        13       2.0.5  a05c1595-3e05-434b-8684-218b528bd725
4            5          XFB2SPiGfjbVhvJ3Q3DBsaT3m2B3                       1329450    ko-US      iOS    16.5.1       2.0.5  EAC6C0B3-7CE8-40EA-8A91-9977C0BA5EF3
...        ...                                   ...                           ...      ...      ...       ...         ...                                   ...
525345  525346          KlGJxOfY4XdbxnwzPckMh4NdwBk2                       1373831    ko-KR      iOS    16.5.1       2.0.5  2EB9127D-703A-495B-8A1E-6667ACA9E724
525346  525347          HGxbSi2oq4MdFVGdQx2UH3f9Aq73                       1043127    en-KR      iOS    16.1.2       2.0.3  4400D84D-0353-49C9-818E-6A45D54F1039
525347  525348  F9EA195C-862F-4572-80A5-C3AE06F83310                           NaN    ko-KR      iOS    16.3.1       2.0.5  F9EA195C-862F-4572-80A5-C3AE06F83310
525348  525349          gQ5GvGk7kGWwnQbOzQ8fxseQp8B2  7m8IwV5H3aaxr1bdPbbkvvJMvtf2       ko  Android        12      1.2.15  eca30324-3b48-41a6-9628-ff663896dd23
525349  525350          8jROJMvKQMgiXMvrXvqDD7o0iWr2                        895807    ko-KR      iOS      16.0       2.0.0  B39CEB8B-2414-4018-91B8-CE1A75F1CCEE

[525350 rows x 8 columns]

In [ ]:
hackle_properties.columns

Index(['id', 'session_id', 'user_id', 'language', 'osname', 'osversion', 'versionname', 'device_id'], dtype='object')

In [ ]:
hackle_properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525350 entries, 0 to 525349
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           525350 non-null  int64
 1   session_id   525350 non-null  object
 2   user_id      443095 non-null  object
 3   language     525350 non-null  object
 4   osname       525350 non-null  object
 5   osversion    525350 non-null  object
 6   versionname  525350 non-null  object
 7   device_id    525350 non-null  object
dtypes: int64(1), object(7)
memory usage: 32.1+ MB